packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.10
  '@better-auth/expo': 1.4.10
  '@eslint/js': ^9.39.2
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-form': ^1.27.7
  '@tanstack/react-query': ^5.90.20
  '@trpc/client': ^11.8.1
  '@trpc/server': ^11.8.1
  '@trpc/tanstack-react-query': ^11.8.1
  '@types/node': ^25.0.3
  '@vitejs/plugin-react': 5.1.2
  better-auth: 1.4.10
  eslint: ^9.39.2
  prettier: ^3.8.1
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: 7.3.1
  zod: ^4.3.5

catalogs:
  react19:
    '@types/react': ^19.2.9
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@shopify/react-native-skia'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
